spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://db:5432/rentals_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres_pass}

resilience4j:
  circuitbreaker:
    instances:
      userService:
        baseConfig: default
        minimumNumberOfCalls: 3
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
      transportService:
        baseConfig: default
        minimumNumberOfCalls: 3
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2