spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://db:5432/users_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres_pass}

  flyway:
    placeholders:
      adminEmail: "admin@ya.ru"
      adminUsername: "admin"
      adminPassword: "12345"